/*
 * Generates the Ed25519 signing key pair for coolFTP Pro licenses. Run once.
 *   node scripts/license/keygen.cjs
 * Writes:
 *   scripts/license/private/signing.pem          private key (git-ignored, keep it secret and backed up)
 *   scripts/license/private/sodium-secret.txt    same key as base64 for the PHP webhook (libsodium format)
 *   packages/core/src/license-pubkey.ts          public key baked into the app and CLI
 */
const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const dir = path.join(__dirname, "private");
const pem = path.join(dir, "signing.pem");
if (fs.existsSync(pem) && !process.env.FORCE) {
  console.error(`Refusing to overwrite ${pem}. Set FORCE=1 to regenerate (all existing license keys would stop verifying).`);
  process.exit(1);
}
fs.mkdirSync(dir, { recursive: true });

const { publicKey, privateKey } = crypto.generateKeyPairSync("ed25519");
const privDer = privateKey.export({ type: "pkcs8", format: "der" });
const pubDer = publicKey.export({ type: "spki", format: "der" });
const seed = privDer.subarray(privDer.length - 32); // PKCS#8 Ed25519: the last 32 bytes are the seed
const pubRaw = pubDer.subarray(pubDer.length - 32); // SPKI Ed25519: the last 32 bytes are the raw key
const sodiumSecret = Buffer.concat([seed, pubRaw]); // libsodium secret key = seed || public key

fs.writeFileSync(pem, privateKey.export({ type: "pkcs8", format: "pem" }), { mode: 0o600 });
fs.writeFileSync(path.join(dir, "sodium-secret.txt"), sodiumSecret.toString("base64") + "\n", { mode: 0o600 });
fs.writeFileSync(
  path.join(__dirname, "..", "..", "packages", "core", "src", "license-pubkey.ts"),
  `// Generated by scripts/license/keygen.cjs. Public half of the Pro license signing key.\nexport const LICENSE_PUBLIC_KEY_B64 = "${pubRaw.toString("base64")}";\n`,
);
console.log("public key :", pubRaw.toString("base64"));
console.log("private key:", pem);
console.log("sodium key :", path.join(dir, "sodium-secret.txt"), "(paste into site/api/config.php)");
